---
abstract: 'File following task for App::MultiModule'
author:
  - 'Dana M. Diederich <dana@realms.org>'
build_requires:
  Test::More: 0
  lib: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.015, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-MultiModule-Tasks-FollowTail
requires:
  App::MultiModule::Task: 0
  Data::Dumper: 0
  HTTP::Server::Simple::CGI: 0
  Message::Transform: 0
  POE: 0
  POE::Wheel::FollowTail: 0
  parent: 0
  perl: 5.006
  strict: 0
  warnings: 0
resources:
  bugtracker: https://github.com/dana/App-MultiModule-Tasks-FollowTail/issues
  homepage: https://github.com/dana/App-MultiModule-Tasks-FollowTail
  repository: https://github.com/dana/App-MultiModule-Tasks-FollowTail.git
version: 1.141220
